#!/bin/bash

# Este script se ejecuta cada 1 minuto
BOOT_SCRIPTS_PATH="/opt/install/bims-boot-scripts"
GIT_COMMIT_LOG_FILE="$BOOT_SCRIPTS_PATH/last_commit.txt"

# Cada 5 Minutos
if [ $(date +%M) -eq 0 ] || [ $(date +%M) -eq 5 ] || [ $(date +%M) -eq 10 ] || [ $(date +%M) -eq 15 ] || [ $(date +%M) -eq 20 ] || [ $(date +%M) -eq 25 ] || [ $(date +%M) -eq 30 ] || [ $(date +%M) -eq 35 ] || [ $(date +%M) -eq 40 ] || [ $(date +%M) -eq 45 ] || [ $(date +%M) -eq 50 ] || [ $(date +%M) -eq 55 ]; then
    # Verificar si el bucket está montado
    /usr/local/sbin/bims_check_cloud_storage

    # Sincronizar los archivos de BIMS
    /usr/local/sbin/bims_sync
fi

# Cada 10 Minutos
if [ $(date +%M) -eq 0 ] || [ $(date +%M) -eq 10 ] || [ $(date +%M) -eq 20 ] || [ $(date +%M) -eq 30 ] || [ $(date +%M) -eq 40 ] || [ $(date +%M) -eq 50 ]; then
    # Se lee el valor del último commit
    LAST_COMMIT=$(cat $GIT_COMMIT_LOG_FILE);

    # Actualiza el Boot Script via GitHub
    cd /opt/install/bims-boot-scripts;
    git pull origin main;

    # Se obtiene el valor del último commit después de la actualización
    NEW_COMMIT=$(git log -1 --pretty=format:"%h - %an, %ar");

    # Si el último commit es diferente al anterior entonces se vuelve a ejecutar boot.sh
    if [ "$LAST_COMMIT" != "$NEW_COMMIT" ]; then
        echo $NEW_COMMIT > $GIT_COMMIT_LOG_FILE;
        bash $BOOT_SCRIPTS_PATH/boot.sh;
    fi
fi